language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-18

script:
  - ./gradlew ":$MODULE:build" ":$MODULE:uploadArchives"

env:
   matrix:
     - MODULE=lib

notifications:
  email: true

sudo: false

cache:
   directories:
        - $HOME/.gradle