
title: Jus
email: a@apptik.io
description: > # this means to ignore newlines until "baseurl:"
  Jus is a flexible and easy HTTP/REST client library for Java and Android.

      it is like Volley but much easier
      it is like Retrofit but infinitely more flexible

  Jus is inspired by the flexibility, modularity and transparency of Google's Volley Library
  and the extreme simplicity of declarative API mapping of Retrofit.
baseurl: "/jus"
url: "http://apptik.io"
twitter_username: apptikProj
github_username:  apptik

# Build settings
markdown: kramdown
theme: minima
