
title: RHub
email: rhub@apptik.io
description: > # this means to ignore newlines until "baseurl:"
  Reactive Hub is a collection of multi-receiver and multi-producer Proxies connecting Publishers
  and Subscribers so that Subscribers can receive events without knowledge of which Publishers, if
  any, there are, while maintaining easily identifiable connection between them.
  It is ideal for centralizing cross-cutting activities
  like UI updates, logging, alerting, monitoring, security, etc.
baseurl: "/RHub"
url: "http://apptik.io"
twitter_username: apptikProj
github_username:  apptik

# Build settings
markdown: kramdown
theme: minima
